<template>
  <div class="palette-show">
  <section>
    <h1>Harmonic Colors Palette </h1>
    <v-color-picker v-model="color" hide-canvas hide-inputs hide-swatches></v-color-picker>
    <span>hue: <input type="number" v-model.lazy="hue" min="0" max="360"></span><br>
    <span>hueComplement: {{hueComplement}}</span><br>
    <span>hueRightAnalogous: {{hueRightAnalogous}}</span><br>
    <span>hueLeftAnalogous: {{hueLeftAnalogous}}</span><br>

    <div><span>primary: {{primary}}</span></div><div class="palette primary"></div><br>
    <div><span>primaryDark500: {{primaryDark500}}</span></div><div class="palette primary-dark500"></div><br>
    <div><span>primaryDark600: {{primaryDark600}}</span></div><div class="palette primary-dark600"></div><br>
    <div><span>secondary: {{secondary }} </span></div><div class="palette secondary"></div><br>
    <div><span>secondaryLight500: {{secondaryLight500 }} </span></div><div class="palette secondary-light500"></div><br>
    <div><span>secondaryLight900: {{secondaryLight900}} </span></div><div class="palette secondary-light900"></div><br>
    <div><span>secondaryDark500: {{secondaryDark500}} </span></div><div class="palette secondary-dark500"></div><br>
    <div><span>accentV1: {{accentV1}} </span></div><div class="palette accentv1"></div><br>
    <div><span>accentV1Light900: {{accentV1Light900}} </span></div><div class="palette accentv1-light900"></div><br>
    <div><span>accentV2: {{accentV2}} </span></div><div class="palette accentv2"></div><br>
    <div><span>accentV2Light900: {{accentV2Light900}}  </span></div><div class="palette accentv2-light900"></div><br>
  </section>
  <section>
    <div>
      <div class="container">
        <h2>Palette Demo</h2>
        <div class="cp-grid">
          <div class="cp-widget cp-grid-col-full">
            <p>Colors on this page are distributed using the 60/30/10 ratio and divided into three categories: primary, secondary, and accent. To provide variety, these categories are further used to generate different tints and shades.</p>
          </div>
          <div class="cp-widget cp-grid-col-full">
            <div id="swatches">
              <div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div><div></div>
            </div>
          </div>
          <div><span class="cp-grid-label">Primary Color</span></div>
          <div class="cp-widget">
            <p>The body background of this page takes the primary color which covers nearly the 60% of the total UI.</p>
          </div>
          <div><span class="cp-grid-label">Secondary Color</span></div>
          <div class="cp-widget">
            <p>A sample paragraph demonstrating the default body text color. Anything that doesn't carry or inherit any text color style will be shown in this color by default.</p>
          </div>
          <div><span class="cp-grid-label">Accent Color</span></div>
          <div class="cp-widget">
            <p>The accent color constitutes about 10% of small but vital details of a UI based on the 60/30/10 rule. <a href="#">Hyperlinks</a> are the most common example where accent is used.</p>
          </div>
          <div><span class="cp-grid-label">Kitchen Sink</span></div>
          <div class="cp-widget">
            <p>Our sweet and simple, regular paragraph element that adopts the secondary color by default.</p>
            <p class="fade-1">A text fragment with a lighter tone of the secondary color. It is generated by using the same hue as the secondary color but adjusting saturation and lightness.</p>
            <p class="cp-box">A highlighted box-like element that uses variations of the primary color as its background and border.</p>
            <p class="cp-box cp-box--dark">Another box element themed using variations of the secondary color.</p>
      
            <a href="#" class="cp-btn">CTA example</a>
          </div>
        </div>
      </div>
     </div>
  </section>
</div>
</template>

<script setup>
  import { ref, reactive, computed, onUpdated } from "vue"

  function hsl(h, s, l) {
    l /= 100;
    const a = s * Math.min(l, 1 - l) / 100;
    const f = n => {
      const k = (n + h / 30) % 12;
      const color = l - a * Math.max(Math.min(k - 3, 9 - k, 1), -1);
      return Math.round(255 * color).toString(16).padStart(2, '0');   // convert to Hex and prefix "0" if needed
    };
    return `#${f(0)}${f(8)}${f(4)}`;
  }


  const color = ref({ h: 200, s: 1, l: 0.5, a: 1 })   
  const hue = computed(() => Math.floor(color.value.h))                                                 // --hue: 250
  const hueComplement = computed(() => hue.value + 100)                           // --hueComplement: calc(var(--hue) + 180)
  const hueRightAnalogous = computed(() => hue.value + 30)                        // --hueRightAnalogous: calc(var(--hue) + 30)
  const hueLeftAnalogous = computed(() => hue.value -30 )                         // --hueLeftAnalogous: calc(var(--hue) - 30)
  const primary = computed(() => hsl( hue.value, 25, 95 ))                        // --primary: hsl(var(--hue) 25% 95%)
  const primaryDark500 = computed(() => hsl( hue.value, 20, 85 ))                 // --primaryDark500: hsl(var(--hue) 20% 85%)
  const primaryDark600 = computed(() => hsl( hue.value, 20, 75 ))                 // --primaryDark600: hsl(var(--hue) 20% 75%)
  const secondary = computed(() => hsl( hue.value, 5, 25 ))                       // --secondary: hsl(var(--hueComplement) 5% 25%)
  const secondaryLight500 = computed(() => hsl( hueComplement.value, 5, 30 ))     // --secondaryLight500: hsl(var(--hueComplement) 5% 30%)
  const secondaryLight900 = computed(() => hsl( hueComplement.value, 5, 95 ))     // --secondaryLight900: hsl(var(--hueComplement) 5% 95%)
  const secondaryDark500 = computed(() => hsl( hueComplement.value, 5, 20 ))      // --secondaryDark500: hsl(var(--hueComplement) 5% 20%)
  const accentV1 = computed(() => hsl( hueRightAnalogous.value, 40, 40 ))         // --accentV1: hsl(var(--hueRightAnalogous) 40% 40%)
  const accentV1Light900 = computed(() => hsl( hueRightAnalogous.value, 40, 95 )) // --accentV1Light900: hsl(var(--hueRightAnalogous) 40% 95%)
  const accentV2 = computed(() => hsl( hueLeftAnalogous.value, 40, 40 ))          // --accentV2: hsl(var(--hueLeftAnalogous) 40% 40%)
  const accentV2Light900 = computed(() => hsl( hueLeftAnalogous.value, 40, 90 ))  // --accentV2Light900: hsl(var(--hueLeftAnalogous) 40% 90%)
</script>
  
<style lang="sass" scoped>
  .palette-show
    display: flex 
  
  .primary
    background-color: v-bind(primary)


  .primary-dark500
    background-color: v-bind(primaryDark500)

  .primary-dark600
    background-color: v-bind(primaryDark600)
  

  .secondary
    background-color: v-bind(secondary)
  

  .secondary-light500
    background-color: v-bind(secondaryLight500)
  

  .secondary-light900
    background-color: v-bind(secondaryLight900)
  

  .secondary-dark500
    background-color: v-bind(secondaryDark500)
  

  .accentv1
    background-color: v-bind(accentV1)
  

  .accentv1-light900
    background-color: v-bind(accentV1Light900)
  

  .accentv2
    background-color: v-bind(accentV2)
  

  .accentv2-light900
    background-color: v-bind(accentV2Light900)
  

  .palette
    height: 40px
    width: 200px
  

  span
    color: v-bind(secondary)

  section 
    padding: 20px
    font: 1em/160% Inter, sans-serif
    background-color: v-bind(primary)
    color: v-bind(secondary)

  a 
    color: v-bind(accentV1)

    &:focus,
    &:hover,
    &:active 
      color: v-bind(accentV2)
    
  p 
    &:not(:last-child) 
      margin-bottom: 1.5em
    
  h1,
  h2,
  h3,
  h4   
    line-height: 120%
    margin-top: 1.5em
    margin-bottom: 1.5rem
    font-weight: bold
    font-family: Nunito, sans-serif
    color: v-bind(secondaryDark500)

  h1 
    font-size: 160%

  h2 
    font-size: 140%

  h3 
    font-size: 120%

  .container 
    margin-right: auto
    margin-left: auto
    max-width: 600px
    padding: 2em

  .cp-grid 
    display: grid
    grid-template-columns: 1fr 3fr
    gap: 2em


  .cp-grid-col-full 
    grid-column: 1 / 3

  .cp-grid-label 
    font-size: 0.75em
    font-family: Nunito, sans-serif
    letter-spacing: 1px
    text-transform: uppercase
    color: v-bind(secondaryLight500)

  .cp-widget 
    &:not(:last-child) 
      padding-bottom: 2em
      border-bottom: 1px solid v-bind(primaryDark500)

  .cp-box 
    padding: 1.5em
    background-color: v-bind(primaryDark500)
    border: 1px solid v-bind(primaryDark600)
    border-radius: 0.25em

    &.cp-box--dark 
      background-color: v-bind(secondaryLight500)
      color: v-bind(secondaryLight900)
      border: 1px solid v-bind(secondary)
    
  .cp-btn 
    padding: 1em 1.5em
    display: inline-flex
    margin: 1em 0
    background-color: v-bind(accentV1)
    color: v-bind(accentV1Light900)
    border-radius: 0.25em
    text-decoration: none
    &:hover,
    &:focus,
    &:active 
      background-color: v-bind(accentV2)
      color: v-bind(accentV2Light900)
    
  #swatches 
    padding: 0.25em
    border: 1px solid v-bind(primaryDark500)
    border-radius: 0.25em
    display: grid
    grid-template-columns: repeat(auto-fit, minmax(30px, 1fr))
    div 
      height: 30px
      &:nth-child(1n) 
        background-color: v-bind(primary) 
      &:nth-child(2n) 
        background-color: v-bind(primaryDark500) 
      &:nth-child(3n) 
        background-color: v-bind(primaryDark600) 
      &:nth-child(4n) 
        background-color: v-bind(secondary) 
      &:nth-child(5n)
        background-color: v-bind(secondaryLight500) 
      &:nth-child(6n)
        background-color: v-bind(secondaryLight900) 
      &:nth-child(7n)
        background-color: v-bind(secondaryDark500) 
      &:nth-child(8n)
        background-color: v-bind(accentV1) 
      &:nth-child(9n)
        background-color: v-bind(accentV1Light900) 
      &:nth-child(10n)
        background-color: v-bind(accentV2) 
      &:nth-child(11n)
        background-color: v-bind(accentV2Light900) 

  
</style>